# -*- coding: utf-8 -*-
"""IMPackaging_Marketing_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrhsaQfjUna3wKb9MVjc3yjTBH1UY02L

# Importing all Neccesory libraries and Data
"""

# To import all required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import pearsonr, ttest_ind

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Import Social Media data
social = pd.read_excel("IM_Packaging_Social_Media.xlsx")

# Import Website Marketing data
website = pd.read_excel("IM_Packaging_Website_Marketing.xlsx")

# Import WhatsApp Marketing data
whatsapp = pd.read_excel("IM_Packaging_WhatsApp_Marketing.xlsx")

# Import YouTube Advertisement data
youtube = pd.read_excel("IM_Packaging_YouTube_Ads.xlsx")

"""# Data Exploration and Cleaning


"""

# Display first five records
print("SOCIAL MEDIA DATA")
print(social.head())

print("\nWEBSITE DATA")
print(website.head())

print("\nWHATSAPP DATA")
print(whatsapp.head())

print("\nYOUTUBE DATA")
print(youtube.head())

#Check Rows and Columns
print("Social Media Shape:", social.shape)
print("Website Shape:", website.shape)
print("WhatsApp Shape:", whatsapp.shape)
print("YouTube Shape:", youtube.shape)

#Check Data Types
print("Social Media Data Types")
print(social.dtypes)

print("\nWebsite Data Types")
print(website.dtypes)

print("\nWhatsApp Data Types")
print(whatsapp.dtypes)

print("\nYouTube Data Types")
print(youtube.dtypes)

#Convert Date Columns
social["Date"] = pd.to_datetime(social["Date"])
website["Date"] = pd.to_datetime(website["Date"])
whatsapp["Date"] = pd.to_datetime(whatsapp["Date"])
youtube["Date"] = pd.to_datetime(youtube["Date"])
#Why: Missing values can create incorrect calculations and problems in machine-learning models.

#Check Missing Values
print("Social Media Missing Values")
print(social.isnull().sum())

print("\nWebsite Missing Values")
print(website.isnull().sum())

print("\nWhatsApp Missing Values")
print(whatsapp.isnull().sum())

print("\nYouTube Missing Values")
print(youtube.isnull().sum())

#there is no null values so no need to delete any rows

#Check Duplicate Records
print("Social Media duplicates:", social.duplicated().sum())
print("Website duplicates:", website.duplicated().sum())
print("WhatsApp duplicates:", whatsapp.duplicated().sum())
print("YouTube duplicates:", youtube.duplicated().sum())

# dont have any duplicate values so no neet to delete any row

#Basic Statistical Summary
print("Social Media Statistical Summary")
print(social.describe())

print("\nWebsite Statistical Summary")
print(website.describe())

print("\nWhatsApp Statistical Summary")
print(whatsapp.describe())

print("\nYouTube Statistical Summary")
print(youtube.describe())

#Why: describe() provides useful statistics such as mean, minimum, maximum, and standard deviation.

"""# Business Quesions & Answers

Q1. How many records and variables are available in each marketing dataset?
"""

print("Social Media:", social.shape)
print("Website:", website.shape)
print("WhatsApp:", whatsapp.shape)
print("YouTube:", youtube.shape)

"""Q2. Are there missing or duplicate records?"""

cleaning_summary = pd.DataFrame({
    "Dataset": ["Social Media", "Website", "WhatsApp", "YouTube"],
    "Missing_Values": [
        social.isnull().sum().sum(),
        website.isnull().sum().sum(),
        whatsapp.isnull().sum().sum(),
        youtube.isnull().sum().sum()
    ],
    "Duplicate_Rows": [
        social.duplicated().sum(),
        website.duplicated().sum(),
        whatsapp.duplicated().sum(),
        youtube.duplicated().sum()
    ]
})

print(cleaning_summary)

"""There is no Missing Values and Duplicate Rows

Q3.Which city generated the highest number of conversions?

1.   Create Chart
2.   Find Best City
"""

city_conversions = social.groupby("City")["Conversions"].sum().sort_values(ascending=False)

print(city_conversions)

plt.figure(figsize=(10, 6))

city_conversions.plot(kind="bar")

plt.title("Conversions by City")
plt.xlabel("City")
plt.ylabel("Total Conversions")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

#Find Best City
best_city = city_conversions.idxmax()
best_city_conversions = city_conversions.max()

print("Best Performing City:", best_city)
print("Total Conversions:", best_city_conversions)

"""Q4.Which marketing platform performed best?

1.   Summarize Main Marketing KPIs for Each plateform
2.   Calculate Conversion Rate


1.   Calculate ROI
2.   Plot ROI




"""

platform_performance = social.groupby("Platform").agg({
    "Impressions": "sum",
    "Clicks": "sum",
    "Leads": "sum",
    "Conversions": "sum",
    "Spend_INR": "sum",
    "Revenue_INR": "sum"
})

print(platform_performance)

platform_performance["Conversion_Rate"] = (
    platform_performance["Conversions"] /
    platform_performance["Leads"] * 100
)

print(platform_performance)

platform_performance["ROI"] = (
    (platform_performance["Revenue_INR"] -
     platform_performance["Spend_INR"])
    / platform_performance["Spend_INR"]
)

print(platform_performance)

plt.figure(figsize=(8, 5))

platform_performance["ROI"].plot(kind="bar")

plt.title("ROI by Social Media Platform")
plt.xlabel("Platform")
plt.ylabel("ROI")

plt.tight_layout()
plt.show()

"""Q5.Is advertising spend correlated with conversions?



"""

#Statistical significance
corr, p_value = pearsonr(
    social["Spend_INR"],
    social["Conversions"]
)

print("Correlation:", corr)
print("P-value:", p_value)

"""Correlation close to +1 = strong positive relationship
Correlation close to 0  = weak/no relationship
Correlation close to -1 = strong negative relationship

**Q6.Can we predict conversions using advertising spend?**

1.   Select variables
2.   Split the data

1.   Create the model
2.   Train the model

1.   Make predictions
2.   Check R²

1.   Regression equation
2.   Regression Visualization
"""

#Select Variables
X = social[["Spend_INR"]]

y = social["Conversions"]

#Split Data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

#Create the model
linear_model = LinearRegression()

#Train Model
linear_model.fit(X_train, y_train)

#Make Prediction
y_pred = linear_model.predict(X_test)

print(y_pred)

#Check R²
r2 = r2_score(y_test, y_pred)

print("R-squared:", r2)

#Regression equation
print("Coefficient:", linear_model.coef_[0])
print("Intercept:", linear_model.intercept_)

#Regression Visualization
plt.figure(figsize=(10, 6))

plt.scatter(
    social["Spend_INR"],
    social["Conversions"]
)

plt.plot(
    X_test,
    y_pred
)

plt.title("Advertising Spend vs Conversions")
plt.xlabel("Advertising Spend (INR)")
plt.ylabel("Conversions")

plt.tight_layout()
plt.show()

"""**Q7.Can we predict conversions using multiple marketing factors?**

1.   Split data
2.   Train Decision Tree Regression


1.   Predictions




"""

features = [
    "Spend_INR",
    "Impressions",
    "Clicks",
    "Leads",
    "Website_Visits"
]

X = social[features]
y = social["Conversions"]

#Split Data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

#Train Decision Tree Regression
tree_model = DecisionTreeRegressor(
    max_depth=4,
    random_state=42
)

tree_model.fit(X_train, y_train)

#Predictions
tree_predictions = tree_model.predict(X_test)

print(tree_predictions)

"""**Q8.Which marketing variables are most important for predicting conversions?**"""

importance = pd.DataFrame({
    "Feature": features,
    "Importance": tree_model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

plt.figure(figsize=(10, 6))

plt.bar(
    importance["Feature"],
    importance["Importance"]
)

plt.title("Marketing Feature Importance")
plt.xlabel("Marketing Feature")
plt.ylabel("Importance")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""**Q9.Did A/B Test Group A or B perform better?**

1.   Compare conversions

1.   Calculate conversion rate for A/B groups
2.   Statistical test


2.   Decision

1.   A/B Test Chart

"""

#Compare conversions
ab_test = social.groupby("AB_Test_Group").agg({
    "Conversions": ["sum", "mean"],
    "Leads": "sum",
    "Spend_INR": "sum",
    "Revenue_INR": "sum"
})

print(ab_test)

#Calculate conversion rate for A/B groups
ab_conversion = social.groupby("AB_Test_Group").agg({
    "Leads": "sum",
    "Conversions": "sum"
})

ab_conversion["Conversion_Rate"] = (
    ab_conversion["Conversions"] /
    ab_conversion["Leads"] * 100
)

print(ab_conversion)

#Statistical test
group_A = social[
    social["AB_Test_Group"] == "A"
]["Conversions"]

group_B = social[
    social["AB_Test_Group"] == "B"
]["Conversions"]

t_stat, p_value = ttest_ind(
    group_A,
    group_B,
    equal_var=False
)

print("T-statistic:", t_stat)
print("P-value:", p_value)

#Decision
if p_value < 0.05:
    print("The difference between A and B is statistically significant.")
else:
    print("The difference between A and B is not statistically significant.")

#A/B Test Chart
ab_conversion["Conversion_Rate"].plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("A/B Test Conversion Rate")
plt.xlabel("A/B Test Group")
plt.ylabel("Conversion Rate (%)")

plt.tight_layout()
plt.show()

"""**Q10.How accurate are our predictive models?**


1.   Linear Regression Evaluation
2.   Decision Tree Evaluation

1.   Create Model Comparison Table





"""

#Linear Regression Evaluation
linear_mae = mean_absolute_error(
    y_test,
    y_pred
)

linear_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred
    )
)

linear_r2 = r2_score(
    y_test,
    y_pred
)

print("Linear Regression")
print("MAE:", linear_mae)
print("RMSE:", linear_rmse)
print("R2:", linear_r2)

#Decision Tree Evaluation
tree_mae = mean_absolute_error(
    y_test,
    tree_predictions
)

tree_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        tree_predictions
    )
)

tree_r2 = r2_score(
    y_test,
    tree_predictions
)

print("\nDecision Tree")
print("MAE:", tree_mae)
print("RMSE:", tree_rmse)
print("R2:", tree_r2)

#Create Model Comparison Table
model_comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree"
    ],
    "MAE": [
        linear_mae,
        tree_mae
    ],
    "RMSE": [
        linear_rmse,
        tree_rmse
    ],
    "R2": [
        linear_r2,
        tree_r2
    ]
})

print(model_comparison)

"""#Predict Future Conversions
(Predict conversions for a future campaign)
"""

future_campaign = pd.DataFrame({
    "Spend_INR": [550],
    "Impressions": [5000],
    "Clicks": [100],
    "Leads": [12],
    "Website_Visits": [80]
})

predicted_conversions = tree_model.predict(
    future_campaign
)

print(
    "Predicted Conversions:",
    predicted_conversions[0]
)

"""#Save Clean Data for MySQL"""

social.to_csv(
    "IM_Packaging_Social_Media_Clean.csv",
    index=False
)

website.to_csv(
    "IM_Packaging_Website_Clean.csv",
    index=False
)

whatsapp.to_csv(
    "IM_Packaging_WhatsApp_Clean.csv",
    index=False
)

youtube.to_csv(
    "IM_Packaging_YouTube_Clean.csv",
    index=False
)
